### ISSUE TITLE
[Help Request] Using a Bookmarklet Java Script 

### ISSUE THREAD

**Issue by FelipeRearden** [ryanpcmcquen/obsidian-custom-javascript#1]
Hello @ryanpcmcquen !!!!

I have a question for you about a idea that I have. I wanna know if your plug-in could help to achieve that.

I'm sorry if is not something related to your plug-in. Feel free to close this Issue if it was the case here :)

I'm a newbie and don't know how to achieve this. 

## The js script

I have a `js script` that transfer the content of a URL in Safari to a new note in Obsidian. This bookmarklet was created by our community friends here:

- This is the forum post: (https://forum.obsidian.md/t/obsidian-web-clipper-bookmarklet-with-full-markdown-support-for-images-headings-and-code-blocks/22068)
- This is the gist for the script: https://gist.github.com/kepano/90c05f162c37cf730abb8ff027987ca3

It's working amazing to transfer content from Safari to Obsidian 

## My Workflow

I have a bunch of URLs in a note in Obsidian that are from an App that I use to listen and "highlight" podcasts (the App generates an URL with the transcript from each highlight that I do from the podcasts episode). For each episode I have 20/30 URL that I use Siri Shortcuts to export than to Obsidian as an `.md` file. 

What I want in this workflow is to extract the content of these URLs to Obsidian Without having to go to Safari. 
- It's the same concept that I show above without using an URL that is is Safari. 

I tried every plugin for extract URL that we have in Obsidian Store and these URLs does not work with them :(

BUT this bookmarklet in able to extract the content just the way that I needed :)

## My Question

I wanna kindly ask your help ...

Is it possible to use your plug-in to run this `js script` while I select (or copy to clipboard) a URL in Obsidian?

If Yes, could you help to achieve this? 🙏🙏🙏

---

Thanks for reading this! Let me know if you need any information. 

Again, I'm sorry if is not something related to your plug-in. Feel free to close this Issue if it was the case here :)

I wish you a fantastic Day!

**Comment by ryanpcmcquen** [comment]
It should be possible to select the URL, then fire the JS with the sidebar button or command. You'll need to adjust the script to make the URL input your selection.

**Comment by FelipeRearden** [comment]
Thanks for your reply.

I will try to talk to the bookmarklet creators in the forum to see if they could help me. 

Unfortunately I dont have code skills to change the code.

**Comment by ryanpcmcquen** [comment]
Let me know if more help is needed here, but I am closing this for now.
