### ISSUE TITLE
Toggle for mobile

### ISSUE THREAD

**Issue by chrisgrieser** [ryanpcmcquen/obsidian-custom-javascript#2]
Thanks for the plugin! 

Could there be a toggle for mobile? Basically, I'd like to run different scripts on Obsidian Desktop and Obsidian Mobile

**Comment by ryanpcmcquen** [comment]
What are you using for syncing? There should be a way to exclude the settings sync with some services.

**Comment by NomarCub** [comment]
There's [this other plugin](https://github.com/mnowotnik/obsidian-user-plugins) with similar features and more recent development. Also, you can write checking if you are on a mobile platform as a part of your script.
